name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Suraysen"

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
        env:
            ConnectionStrings.Default: ${{ secrets.SOME_CONNECTION_STRING }}
            App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}
