name:EchoTest
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  demo-workflow-job:
    steps:
      - name: set echoing of commands on and off


steps:
- name: just echo a message
  run: |
    echo Hello there!
